# Generated by Django 3.2.6 on 2021-08-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('drinking_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PubEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=300)),
                ('date_visited', models.DateTimeField()),
                ('attendees', models.ManyToManyField(to='blog.TeamMember')),
            ],
        ),
    ]
